name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  cloop:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: cloop
      tag-validation: false
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
